version: '3.8'
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: ada_frontend
    ports:
      - 3000:3000
    networks:
      - app_net
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MODEL=$MODEL
        - HUGGINGFACE_TOKEN=$HUGGINGFACE_TOKEN
        - OPEN_API_KEY=$OPEN_API_KEY
    container_name: ada_backend
    restart: unless-stopped
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    networks:
      - app_net
    env_file:
      - .env


networks:
  app_net:
    driver: bridge
